### ISSUE TITLE
How does jsonpath compare to jsonpointer ?

### ISSUE THREAD

**Issue by ant0ine** [yalp/jsonpath#1]
Salut Marc!

Good to see you're writing some Go!
I'm curious, how does jsonpath compare to jsonpointer ?
http://tools.ietf.org/html/draft-pbryan-zyp-json-pointer-02
Seems much more powerful, but not very popular.

A+

Antoine

**Comment by yalp** [comment]
Salut Antoine !

I'm just toying around with Go... I didn't know about jsonpointer, thanks for sharing.

jsonpointer just defines how to access to a single value inside a json document, whereas jsonpath has more powerful features like union (extract multiple values), filters and deep search (recursively match a path).

But jsonpath is missing a proper specification, so some behaviors are implementation specific with some parts heavily depending on some javascript constructs (mainly filters).

@jayway did a good job at setting up a [jsonpath evaluator](http://jsonpath.herokuapp.com/) that lets us test differences between multiple implementations.

**Comment by ant0ine** [comment]
Thanks for the info on JsonPath, this is interesting! I may use it at work.

About JSON pointers, this is one spec in a set of specs around "JSON Schema". (Core, Pointers, References, Validation, HyperSchema) All of this allowing to fully describe a JSON REST API. (http://json-schema.org/) Heroku has done some interesting work around that, you may be interested by their client generation code written in Go (https://github.com/interagent/schematic). BTW, I'm thinking about doing the same thing server side for my framework (https://github.com/ant0ine/go-json-rest)

Anyway, I don't want to pollute your github issues by during them into chats, feel free to close it :)

I hope everything is well, Keep in touch!
