### ISSUE TITLE
License

### ISSUE THREAD

**Issue by je-keller** [yalp/jsonpath#3]
Hi Marc,

I would love to use your jsonpath implementation. Unfortunately I'm not allowed to use Code without proper License. Can you please add one?

Regards

Jan Erik

**Comment by soulne4ny** [comment]
+1

**Comment by je-keller** [comment]
I took my time to rewrite the library:
https://github.com/PaesslerAG/jsonpath
I interpreted the underspecified parts slightly different, but there's a License so feal free to use it.

**Comment by yalp** [comment]
Sorry, I didn't see this earlier (not using this github account that much).
Will add a license so others can fork freely...

Nice work @je-keller sorry you add to rewrite instead of forking ! :/
